### ISSUE TITLE
Permission required.

### ISSUE THREAD

**Issue by labiol** [arielsanchezmora/vDocumentation#33] opened 2018-01-19 10:14 UTC
Permission to perform this operation was denied. Required privilege 'Host.Config.Settings' on managed object with id.
The script works, but a lot of errors appear.

**Comment by arielsanchezmora** [comment] 2018-03-23 14:02
This may be due to settings in your environment. Are you running with a full administrator account on vCenter? Have the hosts been hardened? You can also try to execute the PowerCLI commands from the source code and troubleshoot from there.

**Comment by arielsanchezmora** [comment] 2019-04-30 22:33
I'll close this one as I'm pretty sure the issue is vCenter permissions (try with a full administrator account, or at least read only granted at the vCenter level and inherited everywhere).

**Closed by arielsanchezmora** 2019-04-30 22:33 UTC
