### ISSUE TITLE
Multiple vCenters

### ISSUE THREAD

**Issue by stoneisman** [arielsanchezmora/vDocumentation#34] opened 2018-01-25 15:32 UTC
I would like a way to have all connected vcenters information pulled for each command. Looks like only the last one connected is polled for it's information when you execute a command. I don't see a way to iterate through all connected vcenters or specify multiple datacenters.

**Comment by arielsanchezmora** [comment] 2018-01-26 16:43
Hi! Yup, sounds useful. I *think* we had a way. @edmsanchez do you remember?

**Comment by arielsanchezmora** [comment] 2019-04-30 22:34
I've confirmed this works for me and others, please let us know if you couldn't find the DefaultVIServer variable in PowerCLI and we'll help (maybe in the #vdocumentation channel in the public VMware Code Slack?) but I'll close this one.

**Closed by arielsanchezmora** 2019-04-30 22:34 UTC
